<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'SpressPlugins\\SpressDataLoader\\' => array($baseDir . '/_plugins/Spress-plugin-dataloader'),
);
